# Generated by Django 6.1 on 2026-08-21 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MFADevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=64, verbose_name='secret')),
                ('confirmed', models.BooleanField(default=False, verbose_name='confirmed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmed at')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used')),
                ('last_counter', models.BigIntegerField(default=0, verbose_name='last counter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='djadmin_mfa', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'authenticator',
                'verbose_name_plural': 'authenticators',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to='djadmin.mfadevice')),
            ],
            options={
                'verbose_name': 'recovery code',
                'verbose_name_plural': 'recovery codes',
                'ordering': ('id',),
            },
        ),
    ]
